// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/login-cli.proto

package logincli

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LoginCli service

func NewLoginCliEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LoginCli service

type LoginCliService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (LoginCli_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (LoginCli_PingPongService, error)
}

type loginCliService struct {
	c    client.Client
	name string
}

func NewLoginCliService(name string, c client.Client) LoginCliService {
	return &loginCliService{
		c:    c,
		name: name,
	}
}

func (c *loginCliService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "LoginCli.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginCliService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (LoginCli_StreamService, error) {
	req := c.c.NewRequest(c.name, "LoginCli.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &loginCliServiceStream{stream}, nil
}

type LoginCli_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type loginCliServiceStream struct {
	stream client.Stream
}

func (x *loginCliServiceStream) Close() error {
	return x.stream.Close()
}

func (x *loginCliServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *loginCliServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *loginCliServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *loginCliServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loginCliService) PingPong(ctx context.Context, opts ...client.CallOption) (LoginCli_PingPongService, error) {
	req := c.c.NewRequest(c.name, "LoginCli.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &loginCliServicePingPong{stream}, nil
}

type LoginCli_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type loginCliServicePingPong struct {
	stream client.Stream
}

func (x *loginCliServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *loginCliServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *loginCliServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *loginCliServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *loginCliServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *loginCliServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for LoginCli service

type LoginCliHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, LoginCli_StreamStream) error
	PingPong(context.Context, LoginCli_PingPongStream) error
}

func RegisterLoginCliHandler(s server.Server, hdlr LoginCliHandler, opts ...server.HandlerOption) error {
	type loginCli interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type LoginCli struct {
		loginCli
	}
	h := &loginCliHandler{hdlr}
	return s.Handle(s.NewHandler(&LoginCli{h}, opts...))
}

type loginCliHandler struct {
	LoginCliHandler
}

func (h *loginCliHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.LoginCliHandler.Call(ctx, in, out)
}

func (h *loginCliHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.LoginCliHandler.Stream(ctx, m, &loginCliStreamStream{stream})
}

type LoginCli_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type loginCliStreamStream struct {
	stream server.Stream
}

func (x *loginCliStreamStream) Close() error {
	return x.stream.Close()
}

func (x *loginCliStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *loginCliStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *loginCliStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *loginCliStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *loginCliHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.LoginCliHandler.PingPong(ctx, &loginCliPingPongStream{stream})
}

type LoginCli_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type loginCliPingPongStream struct {
	stream server.Stream
}

func (x *loginCliPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *loginCliPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *loginCliPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *loginCliPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *loginCliPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *loginCliPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
