// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/login-srv.proto

package loginsrv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for LoginSrv service

func NewLoginSrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for LoginSrv service

type LoginSrvService interface {
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type loginSrvService struct {
	c    client.Client
	name string
}

func NewLoginSrvService(name string, c client.Client) LoginSrvService {
	return &loginSrvService{
		c:    c,
		name: name,
	}
}

func (c *loginSrvService) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.name, "LoginSrv.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginSrvService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "LoginSrv.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LoginSrv service

type LoginSrvHandler interface {
	Login(context.Context, *LoginRequest, *LoginResponse) error
	Call(context.Context, *Request, *Response) error
}

func RegisterLoginSrvHandler(s server.Server, hdlr LoginSrvHandler, opts ...server.HandlerOption) error {
	type loginSrv interface {
		Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type LoginSrv struct {
		loginSrv
	}
	h := &loginSrvHandler{hdlr}
	return s.Handle(s.NewHandler(&LoginSrv{h}, opts...))
}

type loginSrvHandler struct {
	LoginSrvHandler
}

func (h *loginSrvHandler) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.LoginSrvHandler.Login(ctx, in, out)
}

func (h *loginSrvHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.LoginSrvHandler.Call(ctx, in, out)
}
